version: "2"
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/shirou)
    goimports:
      # Put imports beginning with prefix after 3rd-party packages.
      local-prefixes:
        - github.com/shirou/gopsutil
issues:
  max-same-issues: 0
linters:
  enable:
    - asciicheck
    - bodyclose
    - contextcheck
    - copyloopvar
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - fatcontext
    - gochecksumtype
    - gocritic
    - godot
    - gomodguard
    - gosec
    - govet
    - importas
    - ineffassign
    - intrange
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - perfsprint
    - predeclared
    - revive
    - staticcheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
  disable: []
  settings:
    gocritic:
      disabled-checks:
        - captLocal
        - commentedOutCode
        - deferInLoop
        - hexLiteral
        - hugeParam
        - tooManyResultsChecker
        - unnamedResult
      enable-all: true
    gomodguard:
      blocked:
        modules:
          - io/ioutil:
              recommendations:
                - io
                - os
    gosec:
      excludes:
        - G115  # Integer overflow conversion - already excluded
        - G304  # File path inclusion - legitimate for system monitoring library
        - G103  # Use of unsafe - needed for endianness detection
        - G104  # Unhandled errors - covered by errcheck linter
        - G204  # Subprocess with variable - legitimate for testing
    govet:
      disable:
        - copylocks
        - fieldalignment
        - testinggoroutine
      enable-all: true
    perfsprint:
      # Optimizes even if it requires an int or uint type cast.
      int-conversion: true
      # Optimizes into `err.Error()` even if it is only equivalent for non-nil errors.
      err-error: true
      # Optimizes `fmt.Errorf`.
      errorf: true
      # Optimizes `fmt.Sprintf` with only one argument.
      sprintf1: true
      # Optimizes into strings concatenation.
      strconcat: true
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
          arguments:
            - allowTypesBefore: "*testing.T"
        - name: context-keys-type
        - name: dot-imports
        - name: duplicated-imports
        - name: early-return
          arguments:
            - "preserveScope"
        - name: empty-block
          disabled: true
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: exported
          disabled: true
        - name: errorf
        - name: increment-decrement
        - name: indent-error-flow
          arguments:
            - "preserveScope"
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: redundant-import-alias
        - name: superfluous-else
          arguments:
            - "preserveScope"
        - name: time-date
        - name: time-equal
        - name: time-naming
        - name: unexported-return
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unused-parameter
        - name: unused-receiver
        - name: use-any
        - name: var-declaration
        - name: var-naming
          arguments:
            - ["ID"] # AllowList
            - ["VM"] # DenyList
            - - upperCaseConst: true # Extra parameter (upperCaseConst|skipPackageNameChecks)
                skipPackageNameChecks: true
    staticcheck:
      checks:
        - all
        - -SA1019 # Using a deprecated function, variable, constant or field
        - -SA2002 # Called testing.T.FailNow or SkipNow in a goroutine, which isn’t allowed
        - -SA4003 # Comparing unsigned values against negative values is pointless
        - -SA4004 # The loop exits unconditionally after one iteration
        - -SA4008 # The variable in the loop condition never changes, are you incrementing the wrong variable?
        - -SA4011 # Break statement with no effect - Windows-specific loop patterns
        - -SA5003 # Defers in infinite loops will never execute
        - -SA9003 # Empty body in an if or else branch
        - -ST1000 # Package comment format - SPDX headers take precedence
        - -ST1003 # Poorly chosen identifier
        - -ST1020 # Comment format for exported functions
        - -ST1021 # Comment format for exported types
        - -ST1022 # Comment format for exported variables
    testifylint:
      enable-all: true
    usetesting:
      os-create-temp: false
      os-mkdir-temp: false
    errcheck:
      # Check type assertions for potential panics from failed assertions
      check-type-assertions: true
      # Don't check for blank assignments (e.g., _ = someFunc())
      check-blank: false
      # Common patterns where error checking is typically omitted
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (net.Listener).Close
        - (net.Conn).Close
        - os.Remove
        - os.RemoveAll
        - purego.Dlclose
        - (*registry.Key).SetDWordValue
        - (*registry.Key).Close
        - (*smc.Connection).Close
        - (*windows.Token).Close
        - windows.LocalFree
        - windows.CloseHandle
        - syscall.CloseHandle
        - (*os.Process).Release
    godot:
      # Comments to be checked: `declarations`, `toplevel`, or `all`.
      scope: declarations
      exclude:
        # Exclude sentence fragments.
        - "^\\+build"
      capital: false
    unconvert:
      # Remove unnecessary type conversions
      fast-math: false
      # Use safe mode to avoid removing conversions that may be needed for certain architectures
      # gopsutil supports many platforms, so we want to be conservative here
      safe: true
  exclusions:
    generated: lax
    rules:
      # Exclude govet shadow warnings for err variable
      - text: 'shadow: declaration of "err" shadows declaration at line'
        linters:
          - govet
      
      # Exclude errname for platform-specific error types/variables (breaking changes)
      - text: 'the error type name `Warnings` should conform to the `XxxError` format'
        linters:
          - errname
      - text: 'the sentinel error name `ErrorNoChildren` should conform to the `ErrXxx` format'
        linters:
          - errname
      - text: 'the sentinel error name `ErrorProcessNotRunning` should conform to the `ErrXxx` format'
        linters:
          - errname
      - text: 'the sentinel error name `ErrorNotPermitted` should conform to the `ErrXxx` format'
        linters:
          - errname
      - text: 'the sentinel error name `loadErr` should conform to the `errXxx` format'
        linters:
          - errname
      
      # Exclude unused for platform-specific invoke variables
      - text: 'var invoke is unused'
        linters:
          - unused
      
      # Exclude unused in test files
      - linters:
          - unused
        path: _test\.go
      
      # Exclude unused for platform-specific code in process package
      - linters:
          - unused
        path: process/process\.go
        text: 'field.*is unused'
      - linters:
          - unused
        path: process/process\.go
        text: 'var.*is unused'
      - linters:
          - unused
        path: process/process_bsd\.go
      - linters:
          - unused
        path: process/process_posix\.go
      - linters:
          - unused
        path: process/process_darwin\.go
      - linters:
          - unused
        path: process/process_windows\.go
      - linters:
          - unused
        path: process/process_freebsd\.go
      - linters:
          - unused
        path: process/process_openbsd\.go
      - linters:
          - unused
        path: process/process_netbsd\.go
      - linters:
          - unused
        path: process/process_aix\.go
      
      # Exclude unused for platform-specific code in other packages
      - linters:
          - unused
        path: host/host\.go
        text: 'func.*is unused'
      - linters:
          - unused
        path: host/host\.go
        text: 'var.*is unused'
      - linters:
          - unused
        path: host/host_windows\.go
      - linters:
          - unused
        path: host/host_aix\.go
      - linters:
          - unused
        path: docker/docker\.go
        text: 'const.*is unused'
      - linters:
          - unused
        path: load/load_bsd\.go
      - linters:
          - unused
        path: disk/disk_aix.*\.go
      - linters:
          - unused
        path: sensors/sensors_aix\.go
      - linters:
          - unused
        path: cpu/cpu\.go
        text: 'func percentUsedFromLastCall is unused'
      - linters:
          - unused
        path: cpu/cpu\.go
        text: 'func convertStatusChar is unused'
      - linters:
          - unused
        path: process/process\.go
        text: 'func convertStatusChar is unused'
      - linters:
          - unused
        path: cpu/cpu_freebsd\.go
      - linters:
          - unused
        path: internal/common/common_windows\.go
      - linters:
          - unused
        path: mem/mem_windows\.go
      - linters:
          - unused
        path: net/net_windows\.go
      - linters:
          - unused
        path: cpu/cpu_windows\.go
      - linters:
          - unused
        path: internal/common/common\.go
        text: 'func attributes is unused'
      
      # Exclude errcheck for Windows syscall cleanup operations (all .Call patterns)
      - text: '\.Call.*is not checked'
        linters:
          - errcheck
      
      # Exclude errcheck for safe conversions and sizeof operations
      - text: 'Error return value of.*unsafe\.Sizeof.*is not checked'
        linters:
          - errcheck
      - text: 'Error return value is not checked.*unsafe\.Sizeof'
        linters:
          - errcheck
      - text: 'Error return value is not checked.*int\(.*\.(DwNumEntries|Table)\)'
        linters:
          - errcheck
      - path: net/net_windows\.go
        linters:
          - errcheck
      - path: winservices/
        text: 'Error return value of `m\.close` is not checked'
        linters:
          - errcheck
      
      # Exclude errcheck for test listener/connection cleanup
      - path: _test\.go
        text: 'Error return value of `l\.Close` is not checked'
        linters:
          - errcheck
      
      # Exclude errcheck for platform-specific cleanup operations
      - text: 'Error return value of `purego\.Dlclose` is not checked'
        linters:
          - errcheck
      - text: 'Error return value of `key\.SetDWordValue` is not checked'
        linters:
          - errcheck
      - text: 'Error return value of `key\.Close` is not checked'
        linters:
          - errcheck
      - text: 'Error return value of `smc\.Close` is not checked'
        linters:
          - errcheck
      - text: 'Error return value of `procFindVolumeClose\.Call` is not checked'
        linters:
          - errcheck
      - text: 'Error return value of `windows\.CloseHandle` is not checked'
        linters:
          - errcheck
      - text: 'Error return value of `windows\.RegCloseKey` is not checked'
        linters:
          - errcheck
      - text: 'Error return value of `procGetNativeSystemInfo\.Call` is not checked'
        linters:
          - errcheck
      - text: 'Error return value of `common\.PdhCloseQuery\.Call` is not checked'
        linters:
          - errcheck
      
      # Exclude unconvert for platform-specific type conversions (safe mode already enabled)
      - text: 'unnecessary conversion'
        linters:
          - unconvert
      
      # Exclude nilerr for platform-specific error handling patterns
      - text: 'error is not nil .* but it returns nil'
        linters:
          - nilerr
      
      # Exclude intrange where function calls may have side effects
      - text: 'for loop can be changed to use an integer range'
        linters:
          - intrange
      
      - text: 'Error return value of `token\.Close` is not checked'
        linters:
          - errcheck
      - text: 'Error return value of `windows\.LocalFree` is not checked'
        linters:
          - errcheck
      
      # Exclude makezero for intentional non-zero slice initialization
      - path: process/process_linux.go
        text: 'append to slice `ret` with non-zero initialized length'
        linters:
          - makezero
      - path: net/net_darwin.go
        text: 'append to slice `ret` with non-zero initialized length'
        linters:
          - makezero
      
      # Exclude mirror for platform-specific string conversion
      - path: process/process_freebsd.go
        text: 'avoid allocations with bytes.IndexByte'
        linters:
          - mirror
      - path: process/process_openbsd.go
        text: 'avoid allocations with bytes.IndexByte'
        linters:
          - mirror
      - path: process/process_darwin.go
        text: 'avoid allocations with bytes.IndexByte'
        linters:
          - mirror
    warn-unused: true
output:
  show-stats: false
run:
  timeout: 5m
