version: "2"
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/shirou)
issues:
  max-same-issues: 0
linters:
  enable:
    - asciicheck
    - contextcheck
    - durationcheck
    - errorlint
    - gocritic
    - gomodguard
    - gosec
    - importas
    - misspell
    - nakedret
    - nolintlint
    - perfsprint
    - predeclared
    - revive
    - staticcheck
    - testifylint
    - thelper
    - unparam
    - usetesting
  disable:
    - errcheck
    - govet
    - ineffassign
    - unused
  settings:
    gocritic:
      disabled-checks:
        - captLocal
    gomodguard:
      blocked:
        modules:
          - io/ioutil:
              recommendations:
                - io
                - os
    gosec:
      excludes:
        - G115
    perfsprint:
      # Optimizes even if it requires an int or uint type cast.
      int-conversion: true
      # Optimizes into `err.Error()` even if it is only equivalent for non-nil errors.
      err-error: true
      # Optimizes `fmt.Errorf`.
      errorf: true
      # Optimizes `fmt.Sprintf` with only one argument.
      sprintf1: true
      # Optimizes into strings concatenation.
      strconcat: true
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
          arguments:
            - allowTypesBefore: "*testing.T"
        - name: context-keys-type
        - name: dot-imports
        - name: duplicated-imports
        - name: early-return
          arguments:
            - "preserveScope"
        - name: empty-block
          disabled: true
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: exported
          disabled: true
        - name: errorf
        - name: increment-decrement
        - name: indent-error-flow
          arguments:
            - "preserveScope"
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: redundant-import-alias
        - name: superfluous-else
          arguments:
            - "preserveScope"
        - name: time-naming
        - name: unexported-return
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unused-parameter
        - name: use-any
        - name: var-declaration
        - name: var-naming
          arguments:
            - ["ID"] # AllowList
            - ["VM"] # DenyList
            - - upperCaseConst: true # Extra parameter (upperCaseConst|skipPackageNameChecks)
    staticcheck:
      checks:
        - all
        # TODO: remove this lines after fixing all the issues
        - -QF1001 # Apply De Morgan’s law
        - -QF1002 # Convert untagged switch to tagged switch
        - -QF1006 # Lift if+break into loop condition
        - -S1001 # Replace for loop with call to copy
        - -SA2002 # Called testing.T.FailNow or SkipNow in a goroutine, which isn’t allowed
        - -SA1019 # Using a deprecated function, variable, constant or field
        - -SA4003 # Comparing unsigned values against negative values is pointless
        - -SA4004 # The loop exits unconditionally after one iteration
        - -SA4006 # A value assigned to a variable is never read before being overwritten. Forgotten error check or dead code?
        - -SA4008 # The variable in the loop condition never changes, are you incrementing the wrong variable?
        - -SA5003 # Defers in infinite loops will never execute
        - -SA9003 # Empty body in an if or else branch
        - -ST1003 # Poorly chosen identifier
        - -ST1005 # Incorrectly formatted error string
        - -ST1017 # Don’t use Yoda conditions
    testifylint:
      enable-all: true
    usetesting:
      os-create-temp: false
      os-mkdir-temp: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    warn-unused: true
output:
  show-stats: false
run:
  timeout: 5m
